### PR TITLE
Enforce throwables/exceptions as rejection reasons

### LINKED ISSUE #46: Enforce \Exception instances as rejection values
This also removes support for rejecting with a Promise instance. 

Decide whether the rejection value is still an optional argument  and can be `null`. Enforcing an argument is more inline with `throw` (you can't throw `null`) and let's us remove `UnhandledRejectionException`.

### PR DESCRIPTION
**Pull request by jsor**
Because rejections are the promise counter parts of throwing an exception, throwables/exceptions should be enforced as rejection reasons.

Also, ReactPHP has always used exceptions as rejection reasons throughout it's components.

Closes #46

### CODE REVIEW

File: src/Exception/CompositeException.php [hunk 1]
```diff
@@ -0,0 +1,31 @@
+<?php
+
+namespace React\Promise\Exception;
+
+class CompositeException extends \Exception
```
Comment (kelunik) [inline src/Exception/CompositeException.php]: How about `MultiReasonException`?

**Comment by clue** [comment]
I like the idea of only accepting `Exception` here, but can you elaborate on the rationale to also support `Throwable`? Thanks!

**Comment by jsor** [comment]
@clue I thought about that myself, but if only `Exception`s are accepted, it's not possible to forward rejections easily.

```php
ini_set('assert.exception', 1);

$promise = new \React\Promise\Promise(function() {
    assert(1 === 0);
});

$nextPromise = $promise->otherwise(function($e) {
    handle($e);

    // $e is AssertionError and can't be passed to reject()
    return \React\Promise\reject($e);
});
```

A solution would be to just rethrow, but that needs to be documented (and the documentation read by the user).

```php
$nextPromise = $promise->otherwise(function($e) {
    handle($e);

    throw $e;
});
```

**Comment by kelunik** [comment]
@clue Why would one want to ***not*** support `Throwable`?

**Comment by WyriHaximus** [comment]
Explicitly not supporting `Throwable`'s would make this PR useless in PHP 7 environments when `TypeError`s bubble up, or anything else from PHP implementing `Throwable`, for example [`Error`](http://php.net/manual/en/class.error.php)

**Comment by stefanotorresi** [comment]
isn't the point of this PR to be *"not longer possible to reject a promise without a reason
or with another promise."* ?
FWIW I think it makes perfectly sense to support `Throwables`. What's the counter argument?

**Comment by clue** [comment]
I didn't mean to question whether supporting `Throwable` is useful here but rather that this is not exactly clear from a consumer perspective (checking just the README). Does it make sense to describe this feature and its implications in the README? :+1:

**Comment by jsor** [comment]
@clue In fact, `\Exception` is only mentioned for PHP 5 support. Where do you want to see more documentation and about what exactly?

File: src/Exception/CompositeException.php [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+
+    /**
+     * @return \Throwable[]|\Exception[]
+     */
+    public function getExceptions()
+    {
+        return $this->exceptions;
+    }
+
+    public static function tooManyPromisesRejected(array $reasons)
```
Comment (clue) [inline src/Exception/CompositeException.php]: `@internal`?

File: src/Exception/InvalidArgumentException.php [hunk 3]
```diff
@@ -0,0 +1,16 @@
+<?php
+
+namespace React\Promise\Exception;
+
+class InvalidArgumentException extends \InvalidArgumentException
+{
+    public static function invalidRejectionReason($reason)
```
Comment (clue) [inline src/Exception/InvalidArgumentException.php]: `@internal`?

File: src/Exception/CompositeException.php (hunk 1 above)
Comment (clue) [reply src/Exception/CompositeException.php]: No objections to either class name, but the use of this class appears a bit unclear. Does it make sense to add documentation for this class and/or mark this class a `@internal`?

File: src/Exception/InvalidArgumentException.php [hunk 4]
```diff
@@ -0,0 +1,16 @@
+<?php
+
+namespace React\Promise\Exception;
+
+class InvalidArgumentException extends \InvalidArgumentException
```
Comment (clue) [inline src/Exception/InvalidArgumentException.php]: The use of this class appears a bit unclear. Do we really need this class? Does it make sense to add documentation for this class and/or mark this class a `@internal`?

File: src/Exception/CompositeException.php (hunk 2 above)
Comment (kelunik) [reply src/Exception/CompositeException.php]: I think something like that makes also sense for custom combinator functions.

File: src/Exception/InvalidArgumentException.php (hunk 4 above)
Comment (jsor) [reply src/Exception/InvalidArgumentException.php]: This is the (slipped in) introduction of named exception constructors (like eg. [doctrine does](https://github.com/doctrine/doctrine2/blob/0c4f9a886682441628f895bda38bdbb3c1703900/lib/Doctrine/ORM/ORMException.php)). I'm going to revert that as it is unrelated to the PR.

Comment (jsor) [reply src/Exception/InvalidArgumentException.php]: Removed in bfe3e98

File: src/Exception/CompositeException.php (hunk 2 above)
Comment (jsor) [reply src/Exception/CompositeException.php]: Name constructor removed in df0976e.

File: src/Exception/CompositeException.php (hunk 1 above)
Comment (jsor) [reply src/Exception/CompositeException.php]: Added documentation in 07b7afd. I think it makes sense to keep it public API is it might be useful for custom collection functions.

**Comment by kelunik** [comment]
@jsor Would you be up for standardizing the `CompositeException` with us @ FIG? We have a `MultiReasonException` that basically does the same. Non-async libraries might also have a use if they invoke several callbacks and only throw an exception for all failed ones afterwards. Standardization could help with building support for this into exception reporting libraries, e.g. https://github.com/symfony/symfony/issues/25883.

**Comment by jsor** [comment]
I've added [WIP] to the PR title. We still need to figure out how we can keep interoperabilty with other promise implementations which allow rejecting with non-exception reasons.

```php
new Promise(function($resolve, $reject) use ($foreignPromise) {
    $foreignPromise->then($resolve, $reject);
});
```

This would now reject `Promise` with a [`\InvalidArgumentException`](https://github.com/reactphp/promise/pull/93/files#diff-1ee10d80b0651bd7c4760d7a6a153290R11) in case `$foreignPromise` is rejected with a non-exception.

One solution would be to wrap the reason in a `ReasonException` as i did here:

https://github.com/jsor-labs/pact/blob/8ec4ea971c9cc08676081d0b5998def26dc4a165/src/Promise.php#L629-L637

**Comment by clue** [comment]
> We still need to figure out how we can keep interoperabilty with other promise implementations which allow rejecting with non-exception reasons.

Do we have a relevant use case where this happens?

**Comment by jsor** [comment]
@clue `Promise\resolve()` for example

https://github.com/reactphp/promise/blob/c1aad8e65d6406fd361f8975194a094d06c83793/src/functions.php#L11-L21

**Comment by clue** [comment]
@jsor It's my understanding that if a foreign promise rejects with something that is not an `Exception`/`Throwable`, the `reject()` method will automatically turn this into an `InvalidArgumentException` with an appropriate message, no? This sounds like a good approach to me!

As far as I can tell, the ecosystem of foreign promises also seem to rely on `Exceptions` for the most part. Consumers that actually need foreign promises with custom rejection reasons can still use an explicit foreign rejection handler and turn this into an appropriate `Exception` type themselves.

Are you seeing anything that is missing here and/or is commonly used in other projects?

**Comment by jsor** [comment]
ping @clue

**Comment by clue** [comment]
One thing: Once this is in, I would like to look into enforcing a `Throwable` type hint here instead of manually throwing an `InvalidArgumentException`. This will likely affect PHP version compatibility, so I think it's best to discuss this in a follow-up ticket :+1:

**Comment by WyriHaximus** [comment]
> One thing: Once this is in, I would like to look into enforcing a `Throwable` type hint here instead of manually throwing an `InvalidArgumentException`. This will likely affect PHP version compatibility, so I think it's best to discuss this in a follow-up ticket

Well either of us can do that, but I'd like to get an PR out A.S.A.P. adding exactly that and raising minimum PHP version to 7.0

**Comment by clue** [comment]
@WyriHaximus Go for it! :shipit:

**Comment by WyriHaximus** [comment]
@clue :tada: !
